services:
  db:
    platform: linux/amd64
    image: mysql:8.0
    container_name: flight_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: airline_reservation
      MYSQL_USER: user
      MYSQL_PASSWORD: root1234
    ports:
      - "3307:3306"  # Changed to 3307
    volumes:
      - db_data:/var/lib/mysql
      - ./flight.sql:/docker-entrypoint-initdb.d/flight.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flight_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/airline_reservation
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: root1234
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  db_data: