version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: flight_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: airline_reservation
      MYSQL_USER: user
      MYSQL_PASSWORD: root1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./flight.sql:/docker-entrypoint-initdb.d/flight.sql

  app:
    build: .
    container_name: flight_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/airline_reservation
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: root1234
    depends_on:
      - db

volumes:
  db_data:
